services:
  backend:
    build: ./backend
    ports:
      - "8123:8123"
    container_name: backend

  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - "8000:8000"
    container_name: frontend